/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 300,
    maxHeight: 300,
    maxWidth: 450,
    minHeight: 300,
    minWidth: 450,
    width: 450,		//	700 -> 450
    title: '환경기초시설 정보',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    height: 245,
                    id: 'grid11',
                    maxHeight: 245,
                    minHeight: 245,
                    autoScroll: true,
                    emptyText: '데이터가 없습니다.',
                    store: 'MyJsonStore',
                    viewConfig: {
                        deferEmptyText: false,
                        emptyText: '<div style="text-align:center;width:100%">데이터가 없습니다.</div>'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'FACI_NM',
                            text: '시설명'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ADDR',
                            text: '주소'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'FACI_AMT',
                            text: '용량(m<sup>3</sup>/일)'
                        },
                       /* {
                            xtype: 'gridcolumn',
                            dataIndex: 'TRT_METHOD_PRE',
                            text: '공정전처리'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'TRT_METHOD_1',
                            text: '공정1차'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'TRT_METHOD_2',
                            text: '공정2차'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'TRT_METHOD_3',
                            text: '공정3차'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'START_DD',
                            text: '가동개시일'
                        },
                       */ {
                            xtype: 'gridcolumn',
                            dataIndex: 'OPR_ORG',
                            text: '운영기관'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                $("#chart11").print();
                            },
                            iconCls: 'excel',
                            text: '엑셀',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var data = Ext.getCmp("grid11").getStore().data.items;

                var html = "<div><table border='1'><thead><tr>";

                html += "<th>시설명</th>";
                html += "<th>주소</th>";
                html += "<th>용량(m<sup>3</sup>/일)</th>";
                /*html += "<th>공정전처리</th>";
                html += "<th>공정1차</th>";
                html += "<th>공정2차</th>";
                html += "<th>공정3차</th>";
                html += "<th>가동개시일</th>";*/
                html += "<th>운영기관</th>";

                html += "</tr>";
                html += "</thead>";
                html += "<tbody>";


                for(var i in data) {
                    html += "<tr>";
                    html += "<td>" + data[i].data['FACI_NM'] + "</td>";
                    html += "<td>" + data[i].data['ADDR'] + "</td>";
                    html += "<td>" + data[i].data['FACI_AMT'] + "</td>";
                   /* html += "<td>" + data[i].data['TRT_METHOD_PRE'] + "</td>";
                    html += "<td>" + data[i].data['TRT_METHOD_1'] + "</td>";
                    html += "<td>" + data[i].data['TRT_METHOD_2'] + "</td>";
                    html += "<td>" + data[i].data['TRT_METHOD_3'] + "</td>";
                    html += "<td>" + data[i].data['START_DD'] + "</td>";*/
                    html += "<td>" + data[i].data['OPR_ORG'] + "</td>";
                    html += "</tr>";
                }

                html += "</tbody></table></div>";

                $(html).find("td").attr("style", "mso-number-format:'\\@'; text-align: center;");

                if($("form[name='excelForm']").length > 0) {
                    $("form[name='excelForm']").remove()
                }

                $("body").append("<form name='excelForm' method='post' target='_blank' accept-charset='EUC-KR'><input type='hidden' id='excel' name='excel'></form>")

                $("#excel").val(
                    $("<div>").append(
                        $(html).clone()
                    ).html()
                );

                document.excelForm.action="/nakdong/exportExcel.do";
                document.excelForm.submit();
    }

});