/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.MyModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'FACI_NM',
            type: 'string'
        },
        {
            name: 'ADDR',
            type: 'string'
        },
        {
            name: 'FACI_AMT',
            type: 'string'
        },
      /*  {
            name: 'TRT_METHOD_PRE',
            type: 'string'
        },
        {
            name: 'TRT_METHOD_3',
            type: 'string'
        },
        {
            name: 'TRT_METHOD_1',
            type: 'string'
        },
        {
            name: 'TRT_METHOD_2',
            type: 'string'
        },
        {
            name: 'START_DD',
            type: 'string'
        },
     */   {
            name: 'OPR_ORG',
            type: 'string'
        }
    ]
});