/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    disableCaching: false,
    enabled: true,
    paths: {
        Ext: '/nakdong/resources/js/lib/extjs-4.1.1',
        'MyApp.store': '/nakdong/resources/js/chart/we/water/new/app/store',
        'MyApp.view': '/nakdong/resources/js/chart/we/water/new/app/view',
        'MyApp.model': '/nakdong/resources/js/chart/we/water/new/app/model'
    }
});


Ext.application({

    requires: [
        'MyApp.view.MyPanel',
        'Ext.Loader'
    ],
    models: [
        'gridModel',
        'chartModel'
    ],
    stores: [
        'chartStore',
        'gridStore'
    ],
    views: [
        'MyPanel'
    ],
    name: 'MyApp',

    launch: function() {
        Ext.create('MyApp.view.MyPanel', {renderTo: Ext.getBody()});
    }

});
