/*
 * File: app/model/chartModel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.chartModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'WMYR',
            type: 'string'
        },
        {
            name: 'WMOD',
            type: 'string'
        },
        {
            name: 'WMWK_1',
            type: 'float'
        },
        {
            name: 'WMWK_2',
            type: 'float'
        },
        {
            name: 'WMWK_3',
            type: 'float'
        },
        {
            name: 'WMWK_4',
            type: 'float'
        }
    ]
});