/*
 * File: app/view/ColumnChart.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ColumnChart', {
    extend: 'Ext.chart.Chart',

    requires: [
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Column'
    ],

    height: 357,
    width: 578,
    animate: true,
    insetPadding: 20,
    store: 'MyJsonStore',
    id : 'chart1',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            axes: [
                {
                    type: 'Category',
                    fields: [
                        'WMYR',
                        'WMOD'
                    ],
                    title: 'Category Axis',
                    position: 'bottom'
                },
                {
                    type: 'Numeric',
                    fields: [
                        'ITEM_BOD'
                    ],
                    title: 'Numeric Axis',
                    position: 'left'
                }
            ],
            series: [
                {
                    type: 'column',
                    label: {
                        display: 'insideEnd',
                        field: 'y',
                        color: '#333',
                        'text-anchor': 'middle'
                    },
                    xField: 'x',
                    yField: [
                        'y'
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});