/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Column',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column'
    ],

    height: 544,
    width: 671,
    title: '중권역 별 좋은물 수질현황',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'top'
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'print',
                            text: '인쇄',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'save',
                            text: '저장',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'chart',
                    dock: 'top',
                    weight: 1,
                    height: 246,
                    id: 'chart1',
                    width: 578,
                    animate: true,
                    insetPadding: 20,
                    store: 'chartStore',
                    axes: [
                        {
                            type: 'Category',
                            fields: [
                                'WMOD'
                            ],
                            grid: true,
                            position: 'bottom'
                        },
                        {
                            type: 'Numeric',
                            fields: [
                                'WMWK_1',
                                'WMWK_2',
                                'WMWK_3',
                                'WMWK_4'
                            ],
                            title: 'BOD',
                            position: 'left'
                        }
                    ],
                    series: [
                        {
                            type: 'column',
                            highlight: true,
                            tips: {
                                trackMouse: true,
                                width: 100,
                                height: 25,
                                titleAlign: 'center',
                                renderer: function(storeItem, item){
                                    var name = storeItem.get('WMYR');
                                    var val;
                                    var type;
                                    
                                    if (item.yField == 'WMWK_1') {
                                        type = '1';
                                        val = storeItem.get('WMWK_1');
                                    }
                                    else if (item.yField == 'WMWK_2') {
                                        type = '2';
                                        val = storeItem.get('WMWK_2');
                                    }
                                    else if (item.yField == 'WMWK_3') {
                                        type = '3';
                                        val = storeItem.get('WMWK_3');
                                    }
                                    else if (item.yField == 'WMWK_4') {
                                        type = '4';
                                        val = storeItem.get('WMWK_4');
                                    }
                                    
                                    this.setTitle(type + "회차 : " + val);
                                }
                            },
                            xField: 'WMOD',
                            yField: [
                                'WMWK_1',
                                'WMWK_2',
                                'WMWK_3',
                                'WMWK_4'
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'excel',
                                    text: '엑셀',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick2,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            height: 215,
                            id: 'grid1',
                            autoScroll: true,
                            title: '',
                            forceFit: true,
                            store: 'gridStore',
                            viewConfig: {
                                deferEmptyText: false,
                                emptyText: '\'<div style="text-align:center;width:100%">데이터가 없습니다.</div>\''
                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'PT_NM',
                                    text: '대표지점'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'WMYR',
                                    text: '연도'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'WMOD',
                                    text: '월'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ITEM_BOD',
                                    text: 'BOD(mg/L)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'GRADE',
                                    text: '등급'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'GRADE_KOR',
                                    text: '비고'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        $("#chart1").print();
    },

    onButtonClick1: function(button, e, eOpts) {
//    	saveImageForExt(671, 246);
    	var chart = Ext.getCmp('chart1');
		saveCharToImage(chart);
    },

    onButtonClick2: function(button, e, eOpts) {
        var data = Ext.getCmp("grid1").getStore().data.items;

        var html = "<div><table border='1'><thead><tr>";

        html += "<th>대표지점</th>";
        html += "<th>연도</th>";
        html += "<th>월</th>";
        html += "<th>BOD(mg/L)</th>";
        html += "<th>등급</th>";
        html += "<th>비고</th>";

        html += "</tr>";
        html += "</thead>";
        html += "<tbody>";


        for(var i in data) {
            html += "<tr>";
            html += "<td>" + data[i].data['PT_NM'] + "</td>";
            html += "<td>" + data[i].data['WMYR'] + "</td>";
            html += "<td>" + data[i].data['WMOD'] + "</td>";
            html += "<td>" + data[i].data['ITEM_BOD'] + "</td>";
            html += "<td>" + data[i].data['GRADE'] + "</td>";
            html += "<td>" + data[i].data['GRADE_KOR'] + "</td>";
            html += "</tr>";
        }

        html += "</tbody></table></div>";

        $(html).find("td").attr("style", "mso-number-format:'\\@'; text-align: center;");

        if($("form[name='excelForm']").length > 0) {
            $("form[name='excelForm']").remove()
        }

        $("body").append("<form name='excelForm' method='post' target='_blank' accept-charset='EUC-KR'><input type='hidden' id='excel' name='excel'></form>")

        $("#excel").val(
            $("<div>").append(
                $(html).clone()
            ).html()
        );

        document.excelForm.action="/nakdong/exportExcel.do";
        document.excelForm.submit();
    }

});