/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.toolbar.Toolbar',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.Legend',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column'
    ],

    width: 617,
    height: 611,
    title: '발생/배출 부하량',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'tabPanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: '소권역별',
                            items: [
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'toolbar',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'print',
                                                    text: '인쇄',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'save',
                                                    text: '저장',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick4,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        },
//                                        {
//                                            xtype: 'chart',
//                                            height: 301,
//                                            id: 'swChart',
//                                            width: 549,
//                                            animate: true,
//                                            insetPadding: 20,
//                                            store: 'swStore',
//                                            theme: 'Base',
//                                            axes: [
//                                                {
//                                                    type: 'Category',
//                                                    fields: [
//                                                        'AS_NM'
//                                                    ],
//                                                    grid: true,
//                                                    title: '',
//                                                    position: 'bottom'
//                                                },
//                                                {
//                                                    type: 'Numeric',
//                                                    fields: [
//                                                        'BOD',
//                                                        'TN',
//                                                        'TP'
//                                                    ],
//                                                    title: '부하량값',
//                                                    position: 'left'
//                                                }
//                                            ],
//                                            series: [
//                                                {
//                                                    type: 'line',
//                                                    title: 'BOD',
//                                                    xField: 'AS_NM',
//                                                    yField: [
//                                                        'BOD'
//                                                    ],
//                                                    smooth: 3
//                                                },
//                                                {
//                                                    type: 'line',
//                                                    title: 'TN',
//                                                    axis: 'left',
//                                                    xField: 'AS_NM',
//                                                    yField: [
//                                                        'TN'
//                                                    ],
//                                                    smooth: 3
//                                                },
//                                                {
//                                                    type: 'line',
//                                                    title: 'TP',
//                                                    axis: 'left',
//                                                    xField: 'AS_NM',
//                                                    yField: [
//                                                        'TP'
//                                                    ],
//                                                    smooth: 3
//                                                }
//                                            ],
//                                            legend: {
//                                                position: 'right'
//                                            },
//                                            listeners: {
//                                                beforerender: {
//                                                    fn: me.onChartBeforeRender,
//                                                    scope: me
//                                                }
//                                            }
//                                        }
                                        
                                        //----------------------------------
                                        {
        									xtype: 'chart',
        									id: 'swChart',
        									draggable: false,
        									animate: true,
        									shadow: true,
        									width: 617,
        									height: 301,
        									store: 'swStore',
        									theme: 'Base',
        				                    legend: {
        						                position: 'bottom'
        						            },
        									axes: [
        										{
        				                            type: 'Category',
        				                            fields: ['AS_NM'],
        				                            position: 'bottom'
        										},
        										{
        											type: 'Numeric',
        				                            fields: ['BOD', 'TN', 'TP'],
        				                            title: '부하량값',
        				                            position: 'left',
        											grid: true,
        				                            label: {
        				                            	renderer: function(value) {
//        					                    			return setComma(value.toFixed(2));
        				                            		return value.toFixed(2);
        				                            	}
        				                            }
        										}
        									],
        				                    series: [
        				                        {
        				                            type: 'column',
        				                            xField: 'AS_NM',
        				                            yField: ['BOD', 'TN', 'TP'],
        											title: ['BOD', 'TN', 'TP'],
                                    				fill: false,
        				                            tips: {
        				                            	trackMouse: true,
        				                            	width: 300,
        				                            	height: 25,
        				                            	titleAlign: 'center',
        				                            	renderer: function(storeItem, item) {
        				                            		var name = storeItem.get('AS_NM');
        				                            		var value = "";
        				                            		
        				                            		var request = new Request();
        				                            		var l_type = request.getParameter('search_type_buha');
        				                            		var l_type_disp="";
        				                            		
        				                            		if(l_type == '01'){
        				                            			l_type_disp = " 발생 부하량(kg/일)";
        				                                    }else{
        				                                    	l_type_disp = " 배출 부하량";
        				                                    }
        				                            		
        				                            		if(item.yField == 'BOD') {
        				                            			name += " BOD" + l_type_disp +": ";
        				                            			value = storeItem.get('BOD');
        				                            		} else if(item.yField == 'TN') {
        				                            			name += " TN" + l_type_disp +": ";
        				                            			value = storeItem.get('TN');
        				                            		} else if(item.yField == 'TP') {
        				                            			name += " TP" + l_type_disp +": ";
        				                            			value = storeItem.get('TP');
        				                            		} 
        				                            		
        													this.setTitle(name + value);
        				                            	}
        				                            }
        				                        }
        				                    ],
        									listeners: {
        										beforerender: {
                                                    fn: me.onChartBeforeRender,
                                                    scope: me
                                                }
        									}        								
        								}
                                        
                                        //--------------------------------------------------------------
                                        
                                        
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: 228,
                                    items: [
                                        {
                                            xtype: 'toolbar',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'excel',
                                                    text: '엑셀',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick3,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            height: 201,
                                            id: 'swGrid',
                                            autoScroll: true,
                                            store: 'swStore',
                                            viewConfig: {
                                                deferEmptyText: false,
                                                emptyText: '<div style="text-align:center;width:100%">데이터가 없습니다.</div>'
                                            },
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'YYYY',
                                                    text: '년도'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'AM_NM',
                                                    text: '중권역'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'BOD',
                                                    text: 'BOD 발생 부하량(kg/일)'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'TN',
                                                    text: 'TN 발생 부하량(kg/일)'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'TP',
                                                    text: 'TP 발생 부하량(kg/일)'
                                                }
                                            ],
                                            listeners: {
                                                beforerender: {
                                                    fn: me.onGridpanelBeforeRender,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: '행정구역별',
                            items: [
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'toolbar',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'print',
                                                    text: '인쇄',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick1,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'save',
                                                    text: '저장',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick5,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        },
//                                        {
//                                            xtype: 'chart',
//                                            height: 301,
//                                            id: 'sidoChart',
//                                            width: 549,
//                                            animate: true,
//                                            insetPadding: 20,
//                                            store: 'sidoStore',
//                                            axes: [
//                                                {
//                                                    type: 'Category',
//                                                    fields: [
//                                                        'CTY_NM'
//                                                    ],
//                                                    position: 'bottom'
//                                                },
//                                                {
//                                                    type: 'Numeric',
//                                                    fields: [
//                                                        'BOD',
//                                                        'TN',
//                                                        'TP'
//                                                    ],
//                                                    title: '부하량값',
//                                                    position: 'left'
//                                                }
//                                            ],
//                                            series: [
//                                                {
//                                                    type: 'line',
//                                                    title: 'BOD',
//                                                    xField: 'CTY_NM',
//                                                    yField: [
//                                                        'BOD'
//                                                    ],
//                                                    smooth: 3
//                                                },
//                                                {
//                                                    type: 'line',
//                                                    title: 'TN',
//                                                    axis: 'left',
//                                                    xField: 'CTY_NM',
//                                                    yField: [
//                                                        'TN'
//                                                    ],
//                                                    smooth: 3
//                                                },
//                                                {
//                                                    type: 'line',
//                                                    title: 'TP',
//                                                    axis: 'left',
//                                                    xField: 'CTY_NM',
//                                                    yField: [
//                                                        'TP'
//                                                    ],
//                                                    smooth: 3
//                                                }
//                                            ],
//                                            listeners: {
//                                                beforerender: {
//                                                    fn: me.onChartBeforeRender1,
//                                                    scope: me
//                                                }
//                                            },
//                                            legend: {
//                                                position: 'right'
//                                            }
//                                        }
                                        
                                        //----------------------------------
                                        {
        									xtype: 'chart',
        									id: 'sidoChart',
        									draggable: false,
        									animate: true,
        									shadow: true,
        									width: 617,
        									height: 301,
        									store: 'sidoStore',
        									theme: 'Base',
        				                    legend: {
        						                position: 'bottom'
        						            },
        									axes: [
        										{
        				                            type: 'Category',
        				                            fields: ['CTY_NM'],
        				                            position: 'bottom'
        										},
        										{
        											type: 'Numeric',
        				                            fields: ['BOD', 'TN', 'TP'],
        				                            title: '부하량값',
        				                            position: 'left',
        											grid: true,
        				                            label: {
        				                            	renderer: function(value) {
//        					                    			return setComma(value.toFixed(2));
        				                            		return value.toFixed(2);
        				                            	}
        				                            }
        										}
        									],
        				                    series: [
        				                        {
        				                            type: 'column',
        				                            xField: 'CTY_NM',
        				                            yField: ['BOD', 'TN', 'TP'],
        											title: ['BOD', 'TN', 'TP'],
                                    				fill: false,
        				                            tips: {
        				                            	trackMouse: true,
        				                            	width: 300,
        				                            	height: 25,
        				                            	titleAlign: 'center',
        				                            	renderer: function(storeItem, item) {
        				                            		var name = storeItem.get('CTY_NM');
        				                            		var value = "";
        				                            		
        				                            		var request = new Request();
        				                            		var l_type = request.getParameter('search_type_buha');
        				                            		var l_type_disp="";
        				                            		
        				                            		if(l_type == '01'){
        				                            			l_type_disp = " 발생 부하량(kg/일)";
        				                                    }else{
        				                                    	l_type_disp = " 배출 부하량";
        				                                    }
        				                            		
        				                            		if(item.yField == 'BOD') {
        				                            			name += " BOD" + l_type_disp +": ";
        				                            			value = storeItem.get('BOD');
        				                            		} else if(item.yField == 'TN') {
        				                            			name += " TN" + l_type_disp +": ";
        				                            			value = storeItem.get('TN');
        				                            		} else if(item.yField == 'TP') {
        				                            			name += " TP" + l_type_disp +": ";
        				                            			value = storeItem.get('TP');
        				                            		} 
        				                            		
        													this.setTitle(name + value);
        				                            	}
        				                            }
        				                        }
        				                    ],
        									listeners: {
        										beforerender: {
                                                    fn: me.onChartBeforeRender1,
                                                    scope: me
                                                }
        									}        								
        								}
                                        
                                        //--------------------------------------------------------------
                                        
                                        
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'toolbar',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'excel',
                                                    text: '엑셀',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick2,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            height: 201,
                                            id: 'sidoGrid',
                                            store: 'sidoStore',
                                            viewConfig: {
                                                deferEmptyText: false,
                                                emptyText: '<div style="text-align:center;width:100%">데이터가 없습니다.</div>'
                                            },
                                            listeners: {
                                                beforerender: {
                                                    fn: me.onGridpanelBeforeRender1,
                                                    scope: me
                                                }
                                            },
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'YYYY',
                                                    text: '년도'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'AM_NM',
                                                    text: '중권역'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'DO_NM',
                                                    text: '시도'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'CTY_NM',
                                                    text: '시군구'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'BOD',
                                                    text: 'BOD '
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'TN',
                                                    text: 'TN'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'TP',
                                                    text: 'TP'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var tabPanel = Ext.getCmp('tabPanel');
        var selectedPanel = tabPanel.getActiveTab();
        if(selectedPanel.title == '소권역별'){
            $("#swChart").print();
        }
    },

    onChartBeforeRender: function(component, eOpts) {
        var request = new Request();
        var type = request.getParameter('search_type_buha');
        var chart = Ext.getCmp('swChart');
        var series = chart.series;
        var aaa = series.items[0];
        
        if(type == '01'){
//            series.items[0].title = series.items[0].title + " 발생 부하량";
//            series.items[1].title = series.items[1].title + " 발생 부하량";
//            series.items[2].title = series.items[2].title + " 발생 부하량";
        	series.items[0].title[0] = series.items[0].title[0] + " 발생 부하량";
        	series.items[0].title[1] = series.items[0].title[1] + " 발생 부하량";
        	series.items[0].title[2] = series.items[0].title[2] + " 발생 부하량";
        }else{
//            series.items[0].title = series.items[0].title + " 배출 부하량";
//            series.items[1].title = series.items[1].title + " 배출 부하량";
//            series.items[2].title = series.items[2].title + " 배출 부하량";
        	series.items[0].title[0] = series.items[0].title[0] + " 배출 부하량";
        	series.items[0].title[1] = series.items[0].title[1] + " 배출 부하량";
        	series.items[0].title[2] = series.items[0].title[2] + " 배출 부하량";
        }
    },

    onButtonClick3: function(button, e, eOpts) {
        var tabPanel = Ext.getCmp('tabPanel');
        var selectedPanel = tabPanel.getActiveTab();
        if(selectedPanel.title == '소권역별'){
            var data = Ext.getCmp("swGrid").getStore().data.items;
            var request = new Request();
            var workType = request.getParameter("search_type_buha");
            var html = "<div><table border='1'><thead><tr>";

            //기본
            html += "<th>년도</th>";
            html += "<th>중권역</th>";
            html += "<th>소권역</th>";
            if(workType == "01"){
                html += "<th>BOD 발생 부하량(kg/일)</th>";
                html += "<th>TN 발생 부하량(kg/일)</th>";
                html += "<th>TP 발생 부하량(kg/일)</th>";
            }else if(workType == "02"){
                html += "<th>BOD 배출 부하량</th>";
                html += "<th>TN 배출 부하량</th>";
                html += "<th>TP 배출 부하량</th>";
            }

            html += "</tr>";
            html += "</thead>";
            html += "<tbody>";

            var columns = new Array();
            columns.push("YYYY");
            columns.push("AM_NM");
            columns.push("AS_NM");
            columns.push("BOD");
            columns.push("TN");
            columns.push("TP");

            for(var i in data) {
                html += "<tr>";

                for(var a = 0; a < columns.length; a++){
                    html += "<td>" + data[i].data[columns[a]] + "</td>";
                }

                html += "</tr>";


            }

            html += "</tbody></table></div>";

            $(html).find("td").attr("style", "mso-number-format:'\\@'; text-align: center;");

            if($("form[name='excelForm']").length > 0) {
                $("form[name='excelForm']").remove();
            }

            $("body").append("<form name='excelForm' method='post' target='_blank' accept-charset='EUC-KR'><input type='hidden' id='excel' name='excel'></form>");

            $("#excel").val(
                $("<div>").append(
                    $(html).clone()
                ).html()
            );

            document.excelForm.action="/nakdong/exportExcel.do";
            document.excelForm.submit();
        }
    },

    onGridpanelBeforeRender: function(component, eOpts) {
        var grid  = Ext.ComponentManager.get("swGrid");
        var store = Ext.data.StoreManager.get("swStore");
        var request = new Request();
        var type = request.getParameter('search_type_buha');

        var type1Columns =[
            {
                xtype: 'gridcolumn',
                dataIndex: 'YYYY',
                width: 60,
                text: '년도'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'AM_NM',
                text: '중권역'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'AS_NM',
                text: '소권역'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'BOD',
                text: 'BOD 발생 부하량(kg/일)',
                width: 115,
                align: 'right'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'TN',
                text: 'TN 발생 부하량(kg/일)',
                width: 115,
                align: 'right'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'TP',
                text: 'TP 발생 부하량(kg/일)',
                width: 115,
                align: 'right'
            }
        ];

        var type2Columns =[
            {
                xtype: 'gridcolumn',
                dataIndex: 'YYYY',
                width: 60,
                text: '년도'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'AM_NM',
                text: '중권역'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'AS_NM',
                text: '소권역'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'BOD',
                text: 'BOD 배출 부하량',
                width: 115,
                align: 'right'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'TN',
                text: 'TN 배출 부하량',
                width: 115,
                align: 'right'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'TP',
                text: 'TP 배출 부하량',
                width: 115,
                align: 'right'
            }
        ];

        if(type == "01"){
            grid.reconfigure(store, type1Columns);
        }else{
            grid.reconfigure(store, type2Columns);
        }

        store.load();
    },

    onButtonClick1: function(button, e, eOpts) {
        var tabPanel = Ext.getCmp('tabPanel');
        var selectedPanel = tabPanel.getActiveTab();
        if(selectedPanel.title == '행정구역별'){
            $("#sidoChart").print();
        }
    },

    onChartBeforeRender1: function(component, eOpts) {
        var request = new Request();
        var type = request.getParameter('search_type_buha');
        var chart = Ext.getCmp('sidoChart');
        var series = chart.series;
        var aaa = series.items[0];

        if(type == '01'){
//            series.items[0].title = series.items[0].title + " 발생 부하량";
//            series.items[1].title = series.items[1].title + " 발생 부하량";
//            series.items[2].title = series.items[2].title + " 발생 부하량";
        	series.items[0].title[0] = series.items[0].title[0] + " 발생 부하량";
            series.items[0].title[1] = series.items[0].title[1] + " 발생 부하량";
            series.items[0].title[2] = series.items[0].title[2] + " 발생 부하량";
        }else{
//            series.items[0].title = series.items[0].title + " 배출 부하량";
//            series.items[1].title = series.items[1].title + " 배출 부하량";
//            series.items[2].title = series.items[2].title + " 배출 부하량";
        	series.items[0].title[0] = series.items[0].title[0] + " 배출 부하량";
            series.items[0].title[1] = series.items[0].title[1] + " 배출 부하량";
            series.items[0].title[2] = series.items[0].title[2] + " 배출 부하량";
        }

    },

    onButtonClick2: function(button, e, eOpts) {
        var tabPanel = Ext.getCmp('tabPanel');
        var selectedPanel = tabPanel.getActiveTab();
        if(selectedPanel.title == '행정구역별'){
            var data = Ext.getCmp("sidoGrid").getStore().data.items;
            var request = new Request();
            var workType = request.getParameter("search_type_buha");
            var html = "<div><table border='1'><thead><tr>";

            //기본
            html += "<th>년도</th>";
            html += "<th>중권역</th>";
            html += "<th>시도</th>";
            html += "<th>시군구</th>";
            if(workType == "01"){
                html += "<th>BOD 발생 부하량(kg/일)</th>";
                html += "<th>TN 발생 부하량(kg/일)</th>";
                html += "<th>TP 발생 부하량(kg/일)</th>";
            }else if(workType == "02"){
                html += "<th>BOD 배출 부하량</th>";
                html += "<th>TN 배출 부하량</th>";
                html += "<th>TP 배출 부하량</th>";
            }

            html += "</tr>";
            html += "</thead>";
            html += "<tbody>";

            var columns = new Array();
            columns.push("YYYY");
            columns.push("AM_NM");
            columns.push("DO_NM");
            columns.push("CTY_NM");
            columns.push("BOD");
            columns.push("TN");
            columns.push("TP");

            for(var i in data) {
                html += "<tr>";

                for(var a = 0; a < columns.length; a++){
                    html += "<td>" + data[i].data[columns[a]] + "</td>";
                }

                html += "</tr>";


            }

            html += "</tbody></table></div>";

            $(html).find("td").attr("style", "mso-number-format:'\\@'; text-align: center;");

            if($("form[name='excelForm']").length > 0) {
                $("form[name='excelForm']").remove();
            }

            $("body").append("<form name='excelForm' method='post' target='_blank' accept-charset='EUC-KR'><input type='hidden' id='excel' name='excel'></form>");

            $("#excel").val(
                $("<div>").append(
                    $(html).clone()
                ).html()
            );

            document.excelForm.action="/nakdong/exportExcel.do";
            document.excelForm.submit();
        }
    },
    
    onButtonClick4 : function(button, e, eOpts){
    	var chart = Ext.getCmp('swChart');
		saveCharToImage(chart);
    },
    
    onButtonClick5 : function(button, e, eOpts){
    	var chart = Ext.getCmp('sidoChart');
		saveCharToImage(chart);
    },

    onGridpanelBeforeRender1: function(component, eOpts) {
        var grid  = Ext.ComponentManager.get("sidoGrid");
        var store = Ext.data.StoreManager.get("sidoStore");
        var request = new Request();
        var type = request.getParameter('search_type_buha');

        var type1Columns =[
            {
                xtype: 'gridcolumn',
                dataIndex: 'YYYY',
                width: 60,
                text: '년도'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'AM_NM',
                text: '중권역'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'DO_NM',
                text: '시도'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'CTY_NM',
                text: '시군구'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'BOD',
                text: 'BOD 발생 부하량(kg/일)',
                align: 'right'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'TN',
                text: 'TN 발생 부하량(kg/일)',
                align: 'right'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'TP',
                text: 'TP 발생 부하량(kg/일)',
                align: 'right'
            }
        ];

        var type2Columns =[
            {
                xtype: 'gridcolumn',
                dataIndex: 'YYYY',
                width: 60,
                text: '년도'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'AM_NM',
                text: '중권역'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'DO_NM',
                text: '시도'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'CTY_NM',
                text: '시군구'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'BOD',
                text: 'BOD 배출 부하량',
                align: 'right'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'TN',
                text: 'TN 배출 부하량',
                align: 'right'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'TP',
                text: 'TP 배출 부하량',
                align: 'right'
            }
        ];

        if(type == "01"){
            grid.reconfigure(store, type1Columns);
        }else{
            grid.reconfigure(store, type2Columns);
        }

        store.load();
    }

});